version: "3"
volumes:
  db-data:
services:
  nginx:
    container_name: bcs-nginx
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www/bcs_application
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./api
    container_name: bcs-php
    ports:
      - 9000:9000
    volumes:
      - ./api:/var/www/bcs_application
      - ~/.bash_history:/root/.bash_history
    restart: on-failure
  database:
    image: mysql:8.0
    container_name: bcs-database
    environment:
      MYSQL_ROOT_PASSWORD: bcsapp
      MYSQL_DATABASE: bcs_application
      MYSQL_USER: bcsapp
      MYSQL_PASSWORD: bcsapp
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    container_name: bcs-phpmyadmin
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
